============================= test session starts ==============================
platform linux -- Python 3.9.15, pytest-7.2.0, pluggy-1.0.0
rootdir: /workspace
collected 8 items
tests/test_a_environment.py ..                                           [ 25%]
tests/test_a_setup.py .                                                  [ 37%]
tests/test_bandit.py ..                                                  [ 62%]
tests/test_q_learning.py F.F                                             [100%]
=================================== FAILURES ===================================
____________________________ test_q_learning_slots _____________________________
>       assert np.argmax(means) == np.argmax(state_action_values)
E       assert 8 == 7
E        +  where 8 = <function argmax at 0x7f4e2df620d0>(array([ 0.97627008,  4.30378733,  2.05526752,  0.89766366, -1.52690401,\n        2.91788226, -1.24825577,  7.83546002,  9.27325521, -2.33116962]))
E        +    where <function argmax at 0x7f4e2df620d0> = np.argmax
E        +  and   7 = <function argmax at 0x7f4e2df620d0>(array([[-1.4350136 ,  6.00935391,  1.61583088, -0.89267992, -1.95053199,\n         2.43990677, -0.86445021,  7.99551049,  6.42089327, -4.23408102]]))
E        +    where <function argmax at 0x7f4e2df620d0> = np.argmax
tests/test_q_learning.py:23: AssertionError
________________________ test_q_learning_deterministic _________________________
>       states, actions, rewards = agent.predict(env, state_action_values)
tests/test_q_learning.py:87:
>       max_list = np.argwhere(self.Q == np.amax(self.Q))
E       AttributeError: 'QLearning' object has no attribute 'Q'
src/q_learning.py:223: AttributeError
=========================== short test summary info ============================
FAILED tests/test_q_learning.py::test_q_learning_slots - assert 8 == 7
FAILED tests/test_q_learning.py::test_q_learning_deterministic - AttributeErr...
========================= 2 failed, 6 passed in 0.92s ==========================